experiment:
  name: "xgboost_housing_price_prediction"
  task: "regression"
  dataset: "housing_data"
  include_date_in_run_name: true

model:
  type: "xgboost"
  params:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8

data_module:
  csv_path: "temp_data/housing_data.csv"
  target_column: "price"
  categorical_columns:
    - "neighborhood"
    - "property_type"
  numerical_columns:
    - "square_feet"
    - "bedrooms"
    - "bathrooms"
    - "year_built"
    - "lot_size"
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15

trainer:
  hyperparameter_tuning:
    enabled: true
    n_trials: 20 