experiment:
  name: "xgboost_housing_price_prediction"
  task: "regression"
  dataset: "housing_data"
  include_date_in_run_name: true
  tags:
    project: "housing_prediction"
    team: "ml_team"
    environment: "development"
  random_seed: 42

model:
  type: "xgboost"
  params:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001

data_module:
  csv_path: "temp_data/housing_data.csv"
  target_column: "price"
  categorical_columns:
    - "neighborhood"
    - "property_type"
  numerical_columns:
    - "square_feet"
    - "bedrooms"
    - "bathrooms"
    - "year_built"
    - "lot_size"
  preprocessing:
    scaling:
      method: "standard"  # Options: standard, minmax, robust
      target_scaling: false
    encoding:
      method: "one_hot"  # Options: one_hot, label, target
      max_categories: 20  # Max unique values before grouping as 'other'
    feature_selection:
      enabled: true
      method: "correlation"  # Options: correlation, variance
      threshold: 0.95  # Correlation threshold or variance threshold
  validation:
    cross_validation:
      enabled: false
      n_folds: 5
      stratified: true
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15
  data_quality:
    outlier_detection:
      enabled: true
      method: "iqr"  # Options: iqr, zscore
      threshold: 1.5  # IQR multiplier or z-score threshold
    missing_values:
      strategy: "mean"  # Options: mean, median, most_frequent
      max_missing_ratio: 0.3  # Maximum ratio of missing values allowed

trainer:
  optimization:
    direction: "minimize"  # For RMSE and other error metrics
  loss_function: "rmse"  # Primary loss function for optimization
  evaluation_metrics:  # Additional metrics to track
    - "mae"
    - "r2"
    - "mape"
  hyperparameter_tuning:
    enabled: true
    n_trials: 20 