services:
  mlflow:
    container_name: ml_training_kit_mlflow
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0
    networks:
      - ml-network
    volumes:
      - ./mlruns:/mlruns  # Persist MLflow data
      - ./mlartifacts:/mlartifacts  # Persist MLflow artifacts

  ml-trainer:
    container_name: ml_training_kit_trainer
    build:
      context: ..
      dockerfile: trad_ml_example/Dockerfile
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - GIT_PYTHON_REFRESH=quiet
    depends_on:
      - mlflow
    networks:
      - ml-network
    volumes:
      - ..:/app  # Mount the entire project directory
      - ./temp_data:/app/trad_ml_example/temp_data  # Mount data directory

networks:
  ml-network:
    name: ml_training_kit_network